language: cpp

env:
  global:
    - CTEST_PARALLEL_LEVEL=4
    - CXX_FLAGS_DEBUG="-O1"

matrix:
  include:
    - name: "OSX - Debug - clang"
      env: BUILD_TYPE=Debug
      os: osx
      compiler: clang

install:
  # Install dependencies for FCL
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then 'ci/install_linux.sh' ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx"   ]; then 'ci/install_osx.sh'   ; fi

script:
  # Create build directory
  - mkdir build
  - cd build

  # Configure
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_FLAGS=-w -DCMAKE_CXX_FLAGS_DEBUG=${CXX_FLAGS_DEBUG} ..

  # Build
  - make -j4 collision

  # Run unit tests
  - travis_wait 30 ./test/collision --run_test=mesh_mesh --log_level=message
